"""create url stats table, add slug_id column to url table and a unique constraint to the otp column in otp table

Revision ID: 112f77a4f63a
Revises: 67f6bba9d03e
Create Date: 2026-05-31 01:27:49.468990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112f77a4f63a'
down_revision: Union[str, Sequence[str], None] = '67f6bba9d03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_stats',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], name='urls_urls_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='url_stats_pk')
    )
    op.create_index('idx_urls_url_id', 'url_stats', ['url_id'], unique=False)
    op.create_unique_constraint("otp_unique_key", 'otp', ['otp'])
    op.add_column('urls', sa.Column('slug_id', sa.UUID(), nullable=False))
    op.create_foreign_key('urls_slugs_id_fk', 'urls', 'slugs', ['slug_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('urls_slugs_id_fk', 'urls', type_='foreignkey')
    op.drop_column('urls', 'slug_id')
    op.drop_constraint("otp_unique_key", 'otp', type_='unique')
    op.drop_index('idx_urls_url_id', table_name='url_stats')
    op.drop_table('url_stats')
    # ### end Alembic commands ###
