"""Initial migartions

Revision ID: 61b1abacfe95
Revises: 040d5f187e33
Create Date: 2026-05-23 00:41:54.223451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b1abacfe95'
down_revision: Union[str, Sequence[str], None] = '040d5f187e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('uuid_generate_v7()')),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pk'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_table('slugs',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('uuid_generate_v7()')),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('custom_slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='slugs_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='slugs_pk'),
    sa.UniqueConstraint('custom_slug')
    )
    op.create_index('idx_slugs_user_id', 'slugs', ['user_id'], unique=False)
    op.create_index('idx_urls_custom_slug', 'slugs', ['custom_slug'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('uuid_generate_v7()')),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('shortened_url', sa.String(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='urls_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='urls_pk'),
    sa.UniqueConstraint('original_url'),
    sa.UniqueConstraint('shortened_url')
    )
    op.create_index('idx_urls_original_url', 'urls', ['original_url'], unique=False)
    op.create_index('idx_urls_shortened_url', 'urls', ['shortened_url'], unique=False)
    op.create_index('idx_urls_user_id', 'urls', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_urls_user_id', table_name='urls')
    op.drop_index('idx_urls_shortened_url', table_name='urls')
    op.drop_index('idx_urls_original_url', table_name='urls')
    op.drop_table('urls')
    op.drop_index('idx_urls_custom_slug', table_name='slugs')
    op.drop_index('idx_slugs_user_id', table_name='slugs')
    op.drop_table('slugs')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
