"""add status column to otp table and remove status column from url status

Revision ID: 67f6bba9d03e
Revises: 6cecc74c5953
Create Date: 2026-05-27 16:53:53.614741

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67f6bba9d03e'
down_revision: str | Sequence[str] | None = '6cecc74c5953'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('valid', 'used', name='otpstatus').create(op.get_bind())
    op.add_column('otp', sa.Column('status', sa.Enum('valid', 'used', name='otpstatus'), nullable=False))
    op.drop_column('urls', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('status', postgresql.ENUM('valid', 'expired', name='urlstatus'), autoincrement=False, nullable=False))
    op.drop_column('otp', 'status')
    # ### end Alembic commands ###
