"""add status to url table and is_deactivated to users table

Revision ID: 6cecc74c5953
Revises: efc1af62e20b
Create Date: 2026-05-26 15:09:13.733946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cecc74c5953'
down_revision: Union[str, Sequence[str], None] = 'efc1af62e20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('valid', 'expired', name='urlstatus').create(op.get_bind())
    op.add_column('urls', sa.Column('status', sa.Enum('valid', 'expired', name='urlstatus'), nullable=False))
    op.add_column('users', sa.Column('is_deactivated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deactivated')
    op.drop_column('urls', 'status')
    # ### end Alembic commands ###
