"""add unqiue constraint to slug_id column in urls table

Revision ID: b6af81294894
Revises: f6f943d690cb
Create Date: 2026-08-18 14:16:30.842704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6af81294894'
down_revision: Union[str, Sequence[str], None] = 'f6f943d690cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("slug_id_unique_key", 'urls', ['slug_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("slug_id_unique_key", 'urls', type_='unique')
    # ### end Alembic commands ###
