"""create url stats table, add slug_id column to url table and a unique constraint to the otp column in otp table

Revision ID: bafceb8dd35d
Revises: 67f6bba9d03e
Create Date: 2026-05-30 16:26:41.839131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafceb8dd35d'
down_revision: Union[str, Sequence[str], None] = '67f6bba9d03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("otp_unique_key", 'otp', ['otp'])
    op.add_column('urls', sa.Column('slug_id', sa.UUID(), nullable=False))
    op.create_foreign_key('urls_slugs_id_fk', 'urls', 'slugs', ['slug_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('urls_slugs_id_fk', 'urls', type_='foreignkey')
    op.drop_column('urls', 'slug_id')
    op.drop_constraint("otp_unique_key", 'otp', type_='unique')
    # ### end Alembic commands ###
