"""add type and delete_at columns to users table and create otp table

Revision ID: efc1af62e20b
Revises: 61b1abacfe95
Create Date: 2026-05-24 04:34:59.909742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc1af62e20b'
down_revision: Union[str, Sequence[str], None] = '61b1abacfe95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('email_signup', 'password_reset', name='otppurpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='otp_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='otp_id_pk')
    )
    op.create_index('idx_auth_otp', 'otp', ['otp'], unique=False)
    sa.Enum('email', 'google', name='usertype').create(op.get_bind())
    op.add_column('users', sa.Column('type', sa.Enum('email', 'google', name='usertype'), nullable=False))
    op.add_column('users', sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete_at')
    op.drop_column('users', 'type')
    op.drop_index('idx_auth_otp', table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
