"""create emails table, add five_days_before and seven_days_before columns to users table and a unique constraint to url_id and date columns for url_stats table

Revision ID: f6f943d690cb
Revises: 112f77a4f63a
Create Date: 2026-06-02 04:06:09.259220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6f943d690cb'
down_revision: Union[str, Sequence[str], None] = '112f77a4f63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processed_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='emails_pk')
    )
    op.create_unique_constraint('url_stats_unique_key', 'url_stats', ['url_id', 'date'])
    op.add_column('users', sa.Column('five_days_before', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('seven_days_before', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seven_days_before')
    op.drop_column('users', 'five_days_before')
    op.drop_constraint('url_stats_unique_key', 'url_stats', type_='unique')
    op.drop_table('emails')
    # ### end Alembic commands ###
